### ISSUE TITLE
[spark] lxd: Unable to load libkmod resources: error -12

### ISSUE THREAD

**Issue by chrisheckler** [juju-solutions/bigtop#52] opened 2018-01-07 00:21 UTC
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ conjure-up --version
conjure-up 2.5.1
$ juju --version
2.3.1-xenial-amd64
$ lxd.lxc --version
2.21

~$ sudo snap list
Name        Version              Rev   Developer  Notes
conjure-up  2.5.1-20180106.0201  919   canonical  classic
core        16-2.30              3748  canonical  core
juju        2.3.1                3106  canonical  classic
lxd         2.21                 5408  canonical  -
```

Getting this error (https://paste.ubuntu.com/26336169/) when spark is deployed to LXD.

To reproduce:
```bash
conjure-up # use lxd/localhost provider
```

choose any bundle with spark and it should fail with this error.

**Comment by chrisheckler** [comment] 2018-01-07 01:09
zookeeper seems to be throwing a similar error

**Comment by adam-stokes** [comment] 2018-01-07 02:48
So I just tried a quick run with conjure-up 2.5.1 on ubuntu 16.04 fresh install:

```
ubuntu@ip-172-31-73-126:~$ conjure-up --color=never --notrack --noreport hadoop-spark localhost test-controller test-model
[info] Summoning hadoop-spark to localhost
[info] Bootstrapping Juju controller.
[info] Bootstrap complete.
[info] Adding machines: 0: (xenial, mem=7G root-disk=32G), 1: (xenial, mem=7G root-disk=32G), 2: (xenial, mem=7G root-disk=32G), 3: (xenial, mem=7G root-disk=32G), 4: (xenial, mem=7G root-disk=32G)
[info] Added machines: 0, 1, 2, 3, 4
[info] Deploying namenode...
[info] Deploying rsyslog...
[info] Deploying spark...
[info] Deploying plugin...
[info] Deploying rsyslog-forwarder-ha...
[info] Deploying ganglia...
[info] Deploying ganglia-node...
[info] Deploying resourcemanager...
[info] Deploying slave...
[info] Deploying client...
[info] rsyslog-forwarder-ha: deployed, installing.
[info] ganglia-node: deployed, installing.
[info] ganglia: deployed, installing.
[info] rsyslog: deployed, installing.
[info] resourcemanager: deployed, installing.
[info] spark: deployed, installing.
[info] namenode: deployed, installing.
[info] client: deployed, installing.
[info] plugin: deployed, installing.
[info] Setting relation client <-> plugin
[info] Setting relation plugin <-> spark
[info] Setting relation plugin <-> resourcemanager
[info] slave: deployed, installing.
[info] Setting relation namenode:juju-info <-> rsyslog-forwarder-ha:juju-info
[info] Setting relation ganglia-node:juju-info <-> namenode:juju-info
[info] Setting relation rsyslog-forwarder-ha:juju-info <-> slave:juju-info
[info] Setting relation ganglia-node:juju-info <-> resourcemanager:juju-info
[info] Setting relation namenode <-> slave
[info] Setting relation namenode <-> resourcemanager
[info] Setting relation resourcemanager <-> slave
[info] Setting relation namenode <-> plugin
[info] Setting relation rsyslog-forwarder-ha:syslog <-> rsyslog:aggregator
[info] Setting relation ganglia-node:juju-info <-> slave:juju-info
[info] Setting relation resourcemanager:juju-info <-> rsyslog-forwarder-ha:juju-info
[info] Setting relation ganglia-node:node <-> ganglia:node
[info] Waiting for deployment to settle.
[info] Model settled.
[info] Running post-deployment steps
[info] Running step: 01_logging after-deploy.
[info] Running step: 02_monitoring after-deploy.
[info] Post-Deployment Step Results
+----------------------+-------------------------------------------------------------------------+
|     Application      |                                  Result                                 |
+----------------------+-------------------------------------------------------------------------+
|  Logging Mechanism   | Rsyslog is now configured. Syslog events are aggregated on: 10.0.94.178 |
| Monitoring Mechanism |       The Ganglia UI is available at: http://10.0.94.178/ganglia.       |
+----------------------+-------------------------------------------------------------------------+
[info] Installation of your big software is now complete.
[warning] Shutting down
```

I couldn't reproduce this error you were seeing though. Here is my juju status output: http://paste.ubuntu.com/26336915/

I'm going to try the other variations now, but if you could get me a tarball of `~/.cache/conjure-up` and what spell you picked (including options) i can try to reproduce that way

**Comment by kwmonroe** [comment] 2018-01-07 03:53
@chrisheckler the spark charm (in fact, all bigtop charms) check for nvidia/cuda hardware with lspci via the `layer-nvidia-cuda` code here:

https://github.com/juju-solutions/layer-nvidia-cuda/blob/master/reactive/cuda.sh#L13

This *should* fail gracefully and simply not attempt to load any cuda bits on non-cuda hardware. So this kind of error is expected:

```
unit-s1-0: 03:31:14 INFO unit.s1/0.juju-log Invoking reactive handler: reactive/cuda.sh "b'check_cuda_support\n'"
unit-s1-0: 03:31:15 DEBUG unit.s1/0.update-status lspci: Unable to load libkmod resources: error -12
unit-s1-0: 03:31:15 DEBUG unit.s1/0.update-status Running reactive_handler_main for cuda.sh (invoke)
unit-s1-0: 03:31:15 DEBUG unit.s1/0.update-status Invoking bash reactive handler: check_cuda_support
unit-s1-0: 03:31:15 INFO unit.s1/0.juju-log This instance does not run an nVidia GPU.
unit-s1-0: 03:31:15 DEBUG unit.s1/0.update-status End reactive_handler_main (invoke)
```

I've deployed the latest spark bits with lxd (both with conjure-up and without), and have the same findings as @battlemidget. The deployment completes successfully; the debug log reports the above "error", but it doesn't affect the functionality of spark (other than cuda acceleration is obviously not available).

If your spark deployment is not functional, please pastebin the output from:

```
juju debug-log -i spark/0 --replay
```

Any `lspci` issues are red-herrings and *should not* cause a spark deployment failure.

**Comment by chrisheckler** [comment] 2018-01-07 21:30
This is interesting.  Let me add some context.  Everything works great on my personal laptop with juju, lxd and conjure-up versions the same on my ubuntu 16.04 machine.

The machine with the issue is running ubuntu-16.04.3-server-amd64 which may have an effect.

Furthermore, this issue is not limited to spark but hadoop as well  when I deploy 
```bash 
juju deploy hadoop-spark
```
I find that hadoop-namenode fails to start and is blocked.  Which leads me to believe that there is a deeper issue with the main app by itself and in a bundle.

Here is my output for 
```bash
juju debug-log -i spark/0 --replay
```
https://paste.ubuntu.com/26342301/

Here is also my output for 
```bash
/.cache/conjure-up/conjure-up.log
``` 
http://paste.ubuntu.com/26342424/

Here is my output for
```bash
juju debug-log -i namenode/0
```
http://paste.ubuntu.com/26342569/

Here is my ``` juju status ``` for the ```juju deploy hadoop-spark``` namenode/0 error
http://paste.ubuntu.com/26343536/

If more data is needed I will be happy to oblige.

**Comment by chrisheckler** [comment] 2018-01-15 00:40
per https://github.com/conjure-up/spells/issues/130, looks like my modem is handing out fqdns to my lxd that cannot be resolved.

Looks like the fix is for me to get a real router.

You can close this bug if you like, but it may be useful for others to know that if you are directly behind a comcast modem and bridging to lxd, you will get failed deploys. 

Thanks!

**Comment by jamesbeedy** [comment] 2018-01-22 19:33
this is this is https://github.com/juju-solutions/jujubigdata/issues/62

**Comment by kwmonroe** [comment] 2018-02-01 22:48
Thanks for the report @chrisheckler.  As mentioned, this isn't an issue with lspci/libkmod in the bigtop charms, but rather a more fundamental issue with dns in big data clusters.  I'm closing this out as we're tracking this is in the jujubigdata repo.

**Closed as completed by kwmonroe** 2018-02-01 22:48 UTC
